centralSecurityServices:
  delegatedAdminAccount: Audit
  ebsDefaultVolumeEncryption:
    enable: false
    excludeRegions: []
  s3PublicAccessBlock:
    enable: true
    excludeAccounts: []
  scpRevertChangesConfig:
    enable: false
  snsSubscriptions: []
  macie:
    enable: false
    excludeRegions: []
    policyFindingsPublishingFrequency: FIFTEEN_MINUTES
    publishSensitiveDataFindings: true
  guardduty:
    enable: true
    excludeRegions:
      - us-east-1
    s3Protection:
      enable: true
      excludeRegions: []
    exportConfiguration:
      enable: true
      overrideExisting: true
      destinationType: S3
      exportFrequency: FIFTEEN_MINUTES
  securityHub:
    enable: false
    # regionAggregation: false
    # # excludeRegions: []
    standards: []
  ssmAutomation:
    excludeRegions: []
    documentSets: []
accessAnalyzer:
  enable: false
iamPasswordPolicy:
  allowUsersToChangePassword: true
  hardExpiry: false
  requireUppercaseCharacters: true
  requireLowercaseCharacters: true
  requireSymbols: true
  requireNumbers: true
  minimumPasswordLength: 15
  passwordReusePrevention: 24
  maxPasswordAge: 90
awsConfig:
  enableConfigurationRecorder: false
  ruleSets: []
cloudWatch:
  metricSets: []
  alarmSets: []
  logGroups:
    # At present, OU targetting does not work - AWS bug
    # 09-logging-vpcFlowlogsLogGroup
    - logGroupName: aws-lza-vpc-flowlogs
      logRetentionInDays: 90
      terminationProtected: false
      encryption:
        useLzaManagedKey: true
      deploymentTargets:
        accounts:
          - LogArchive
          - Audit
          - Training

keyManagementService:
  keySets: []
  # # 04-account-setup-localEbsKey
  # - name: aws-lza-ebs-key
  #   deploymentTargets:
  #     organizationalUnits:
  #       - Sandbox
  #   alias: alias/aws-lza-ebs
  #   policy: kms-key-policies/04-account-setup-aws-lza-ebs-key-policy.json
  #   description: ABS Account EBS Encryption Key
  #   enabled: true
  #   enableKeyRotation: true
  #   removalPolicy: destroy
